CREATE TABLE IF NOT EXISTS USERS (
ID UUID PRIMARY KEY,
NAME VARCHAR(255) NOT NULL,
EMAIL VARCHAR(255) NOT NULL UNIQUE,
PASSWORD VARCHAR(255) NOT NULL,
CREATED TIMESTAMP NOT NULL,
MODIFIED TIMESTAMP,
LAST_LOGIN TIMESTAMP,
TOKEN VARCHAR(255),
IS_ACTIVE BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS PHONES (
ID UUID PRIMARY KEY,
USER_ID UUID NOT NULL,
PHONE_NUMBER VARCHAR(50) NOT NULL,
CITY_CODE VARCHAR(10),
COUNTRY_CODE VARCHAR(10),
CONSTRAINT FK_PHONES_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);
